timer:
  seconds: 10  # Combat duration after last hit
  include-victim: false # If true, victim also gets combat-tagged

command-block:
  allow: # Allowed during combat
    - "/msg"
    - "/r"
    - "/tell"
    - "/help"

